-- Phase 36 tenant isolation kernel.
-- Identity: tenants, users, memberships. Discriminator: leagues.tenant_id.
-- Children inherit the tenant through their league, which is what makes a
-- cross-tenant composite FK expressible as a constraint rather than a hope.

CREATE TABLE IF NOT EXISTS tenants (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug        text NOT NULL UNIQUE,
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS users (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email       text NOT NULL UNIQUE,
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS memberships (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id   bigint NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  user_id     bigint NOT NULL REFERENCES users(id)   ON DELETE CASCADE,
  role        text NOT NULL DEFAULT 'member',
  UNIQUE (tenant_id, user_id)
);

-- The discriminator. NOT NULL: a league with no tenant is invisible to every
-- policy and therefore to everyone, which fails closed but silently; refusing
-- the row is louder and cheaper.
ALTER TABLE leagues ADD COLUMN IF NOT EXISTS tenant_id bigint REFERENCES tenants(id);

-- Immutable ownership: a league's tenant cannot be repointed by an UPDATE.
-- Phase 36 names an explicit transfer contract; until that exists, the answer
-- to "can a league be moved between tenants" must be no, enforced.
CREATE OR REPLACE FUNCTION forbid_tenant_repoint() RETURNS trigger AS $$
BEGIN
  IF NEW.tenant_id IS DISTINCT FROM OLD.tenant_id THEN
    RAISE EXCEPTION 'league ownership is immutable (tenant % -> %)', OLD.tenant_id, NEW.tenant_id
      USING ERRCODE = 'check_violation';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS leagues_tenant_immutable ON leagues;
CREATE TRIGGER leagues_tenant_immutable BEFORE UPDATE ON leagues
  FOR EACH ROW EXECUTE FUNCTION forbid_tenant_repoint();

-- A composite unique the children can point at, so a child row cannot name a
-- (league, tenant) pair that does not exist.
CREATE UNIQUE INDEX IF NOT EXISTS uq_league_id_tenant ON leagues (id, tenant_id);
